SELECTION-SCREEN BEGIN OF BLOCK b1.
  PARAMETER: p_1bim(12) TYPE p DECIMALS 2.
  PARAMETER: p_2bim(12) TYPE p DECIMALS 2.
  PARAMETER: p_3bim(12) TYPE p DECIMALS 2.
  PARAMETER: p_4bim(12) TYPE p DECIMALS 2.
SELECTION-SCREEN END OF BLOCK b1.